### CREATE five documents.
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Sorry to Bother You",
    "year": 2019,
    "language": "English"
}


### CREATE 2
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Eternal Sunshine Of The Spotless Mind",
    "year": 2004,
    "language": "Arabic"
}

### CREATE 3
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "High Fidelity",
    "year": 2000,
    "language": "French"
}

### CREATE 4
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Anchorman",
    "year": 2004,
    "language": "Korean"
}

### CREATE 5
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Parasite",
    "year": 2019,
    "language": "Korean"
}


### RETRIEVE all documents.
GET http://localhost:3000/movies HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/movies/64b1858266bab09458b3a96e HTTP/1.1


### UPDATE one document's year, by ID.
### Replace the ID in the following request with one that exists
### and update the year:
PUT http://localhost:3000/movies/64b1857a66bab09458b3a966 HTTP/1.1
content-type: application/json

{
    "title": "Sorry to Bother You",
    "year": 2016,
    "language": "English"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/movies/64b1857a66bab09458b3a966 HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/movies HTTP/1.1

